### ISSUE TITLE
[Documentation] Kuroisan

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/Tactics-Remix#11]
I love Kuroisan. He is my favourite enemy from the mod.

I read the recent news that you modified the release in regards to the difficulty slider.

Could you perhaps clarify in the README what this means? How many allies may he
bring? How much more difficult may it be? I initially played it on second highest
difficulty I think and Kuroisan was too strong until I got some breach magic, then
it was doable. I wonder how much harder he may be with allies though.

**Comment by morpheus562** [comment]
On Insane or higher, he will bring 3 floating sword companions that deal their own unique on-hit effects. They have 36hp and are 90% resistant to all damage types. On one difficulty level less than Insane, he will randomly bring only one of the three swords.

**Comment by morpheus562** [comment]
I like a certain level of ambiguity as I want players to experience the new encounter without knowing exactly what is coming right before it hits.
