### ISSUE TITLE
Improved Irenicus: dragon?

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/Tactics-Remix#13]
When I did a recent play through, I think Improved Irenicus also
had a dragon companion. This one was unbeatable to me on
insane difficulty. Could this companion be changed to some 
other monster type? I did not expect a strong dragon to be
with Irenicus, and I had to stop playing at that point (I think
I also tried to reduce difficulty level but still could not beat
that dragon).

I understand that tactics means tactics, but some of it was
more like mission impossible. Other challenges, including
the dragons at the world map mountain pass gate, I could
go through eventually, but there are just too many strong
opponents with that dragon, in my opinion.

Tactics remix mod is an interesting mod but some of it
can seem just unfair.

**Comment by morpheus562** [comment]
Did you play version 0.6-beta or later, or did you play the earlier alpha release?
