### ISSUE TITLE
Kuroisan won't emerge again

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/Tactics-Remix#14]
I played through tactics remix a few times.

Kuroisan is great; I always seek to take his katana now. :P

Unfortunately he seems to not want to respawn, after 
having made a few appearances. Perhaps he is stuck
or something; or there are finite respawn numbers for
him to spawn?

If so perhaps these could be increased, and an additional
check could be added or something for Kuroisan to respawn
if he is still alive, after chapter 6 or so. Right now I have to
play without seemingly able to find him (not sure what happened
to Kuroisan; he may have relocated to some area where I can
not find him).

I don't know the scripting language used by Baldur's gate engine;
I should learn it to be able to more meaningfully contribute 
patches. Hopefully the feedback is useful in any way - please
feel free to close/ignore/proceed with this issue request as
you see fit. Tactics remix is a very nice mod in general - it just
seems a bit too difficult sometimes. (Poison encounter can be
difficult too but there are ways to deal with poison, so it's ok.)

**Comment by morpheus562** [comment]
How many appearances has he made in your game?
