### ISSUE TITLE
[Quest-like overview for the tactics-remix or item for a quest-like overview of enemies of this mod]

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/Tactics-Remix#15]
Sorry for spamming down the issue tracker. :D

As always please feel free to ignore, change or adapt any way how you see fit.

I would like to ask whether a "todo list" could be added to the tactics remix mod.

Normally quests are registered in the journal entry and via a shortcut key the
player can view it. Now, tactics remix does not have quests like in a journal 
entry, but my idea is kind of roughly to keep ONE page there (so only one
drop down entry), in the journal, and re-assemble it depending on the 
player's progress.

For instance I was not sure whether I killed Kuroisan 2 days (in reallife) ago,
and when there are many quests and mods installed, it can be confusing
to keep track of things without making notes (or using the in-game journal).

So what could perhaps be done is this:

"Finesse and Tactics are what separates the expert from the youngling."

As a generic intro text, just as an example.

And then, entries are kept, like this:

"On the day xx.yy.zzzz, a Kai-master by the name Kuroisan was killed by
our group."

And for the gnome:

"On the day xx.yy.zzzz, a Kai-gnome by the name [Whatever] was killed by
our group."

Same for the lichs, dragons and what not. These may be registered in
addition to regular quest-entries in the journal (such as Kangaxx or
whatever was his name), or simply kept separate.

I am not sure how much work it is to add these. You mentioned in a 
forum that you don't plan to modify the mod in regards to additional
encounters and what not and may focus on re-adjusting balance and
items and so forth. So this may be out of scope of the limitation of
your time investment. On the other hand perhaps it is easy to do,
if another mod makes something similar, and then the text above
could be applied onto it. There is probably some way to obtain the
in-game time; I think a few other mods or quests do that, at the
least the time/date entry is kept in the main journal.

If the above is too difficult then perhaps some kind of ad-hoc item
diary could be kept, like an item like this:

"You see an old parchment of famous enemies in the lands:"

Then a listing of these famous enemies in a one-entry-per-line.

And if one of those enemies is slain, such as Kuroisan, the 
content of that item can be extended such as:

"You see an old parchment of famous enemies in the lands:"

    Kuroisan (deceased)

or

    Kuroisan (confirmed dead)

So an item may be easier to add than a journal entry.

That item could be passed by a new ad-hoc NPC who may appear when
the party enters the docks or so. The NPC may be an aging bounty hunter
who killed an enemy kai-master (let's call him Furuzi or Asanthe or any
name like that, and think of him as a ninja ... aka some person wearing
black garment), who was permanently blinded in his last encounter, 
and passes on the parchment to the party. Bla bla bla "please, try to
stop those on these lists - they are a threat to the world, mighty heroes".
Or something like that. A reward may also be obtained if one kills ALL
listed enemies, but that should not be a huge reward, perhaps an item
of semi-usefulness, perhaps a charged item to make it not too dominant
for all of the gameplay.

Anyway, just some rough ideas. With a journal entry or an item, the
remix mod may get a little bit of a "real" introduction.

**Comment by morpheus562** [comment]
None of these encounters are really quest worthy (outside of Red Badge and The Ritual which add quests). Tactics behaves in-line with existing BGEE and BG2EE in regards that not every fight gets added to the character's journal.
