### ISSUE TITLE
[Possibly a bug, not sure, or an oversight] Kuroisan's blade companions seem vulnerable against poison effects

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/Tactics-Remix#18]
Paina, from another mod, can summon lots of small spiders, with poison. When I hasted them recently,
I was able to easily surround the three blades and the spiders bit them to death (and also prevented them
from reaching my party). I haven't yet fought Kuroisan with this tactic, and it may not be useful due to the
acid area-based damage, but at the least the three standalone companions left over from an area can
be killed via these small spiders easily. Just reporting this here to let you know - perhaps there may be
more poison effects that are useful (like from the red badge encounter, even though that is just
one spear; but perhaps some spells that can be used, I may try more in my current run through, in
regards to the magical companions of Kuroisan.)

**Comment by morpheus562** [comment]
Thank you. I am closing this as it is not an issue.
